version: "2.0"
services:
  client:
    image: reagancn/telegram-gpt:latest
    container_name: bot-client
    restart: on-failure
    networks:
    - telegpt-network
    tty: true
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    volumes:
      - backend-mongodb:/data/db
    networks:
    - telegpt-network
networks:
  telegpt-network: {}
volumes:
  backend-mongodb: